name: flutter_event_calendar
description: Gregorian and Jalali Event calendar for flutter with options for change style
version: 0.0.8
homepage: https://github.com/novaday-co/flutter_event_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  scoped_model: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  shamsi_date: ^1.0.1
  persian_number_utility: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
